# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_publique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_lien',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image/affiche-warriors-movie.jpeg', upload_to='image'),
        ),
    ]
