# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('icon', models.CharField(help_text='Consultez la liste des logo possible <a href="https://fontawesome.com/icons?d=gallery">ici</a>', max_length=30)),
            ],
        ),
    ]
