# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-03 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie'),
            preserve_default=False,
        ),
    ]
