# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture', models.CharField(default='http://lgdclefilm.pythonanywhere.com/static/image/default_blanket.jpg', max_length=400)),
                ('titre', models.CharField(max_length=200)),
                ('quatrieme_de_couverture', models.TextField()),
                ('_description_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('description', precise_bbcode.fields.BBCodeTextField(no_rendered_field=True)),
            ],
        ),
    ]
