# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-26 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_livres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.CharField(default='http://lgdclefilm.pythonanywhere.com/static/image/defaut_background.jpg', max_length=400)),
            ],
        ),
    ]
