# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-27 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_cycle_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='livres',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
