# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_livres_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='livres',
            name='tome',
            field=models.CharField(default=1, help_text='chiffre entre 1 et 9, pour les HS mettre le numero de parution', max_length=2),
            preserve_default=False,
        ),
    ]
