# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_livres_tome'),
    ]

    operations = [
        migrations.AddField(
            model_name='livres',
            name='auteur',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
