# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-02 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_livres_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livres',
            name='date_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de parution anglaise'),
        ),
        migrations.AddField(
            model_name='livres',
            name='date_fr',
            field=models.CharField(default=1, max_length=200, verbose_name='date de parution française'),
            preserve_default=False,
        ),
    ]
