# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20190202_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='livre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Livres'),
        ),
        migrations.AddField(
            model_name='livres',
            name='commentaires',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
