# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-09 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20190209_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='livre',
        ),
    ]
